### ISSUE TITLE
typos in sample data comment

### ISSUE THREAD

**Issue by PixelPartner** [mzaks/FlexBuffersSwift#4]
Shouldn't it read
// {vec:[-100,"Fred",4.0], bar:[1,2,3], bar3:[1,2,3], foo:100, mymap:{foo:"Fred"}}
instead of
// {vec:[-100,"Fred",4.0],bar:[1,2,3],bar3:[1,2,3]foo:100,mymap{foo:"Fred"}}

**Comment by mzaks** [comment]
Thanks!
fixed it.
