### ISSUE TITLE
Special character é 

### ISSUE THREAD

**Issue by tak3mat3k** [mzaks/FlexBuffersSwift#6]

**Comment by tak3mat3k** [comment]
"Caf\\u00e9" Café isn't handled

**Comment by mzaks** [comment]
Is it not handled while decoding from JSON?
Could you please provide a specific sample or even create a pull request with failing unit test?
You can use 
https://github.com/mzaks/FlexBuffersSwift/blob/master/FlexBuffersTests/escaping.json
And 
https://github.com/mzaks/FlexBuffersSwift/blob/master/FlexBuffersTests/JsonToFlexConverterTest.swift#L182

Or if it is in code please have a look at:
https://github.com/mzaks/FlexBuffersSwift/blob/master/FlexBuffersTests/JsonToFlexConverterTest.swift#L61

**Comment by mzaks** [comment]
This bug is solved in release 0.4.1 how ever there is another issue which is a total yak shaving problem 🙃
https://github.com/mzaks/FlexBuffersSwift/issues/7
